### ISSUE TITLE
Annotations issues in Silex (Class  xxx is not a valid entity or mapped super class )

### ISSUE THREAD

**Issue by julietaCuadrado** [Taluu/nutwerk-orm-extension#1]
Hello,
First of all, thanks for your work.

I'm using this provider with Silex and JMSSerializerBundle, thus I need to swich from `@Entity` to `@ORM\Entity` notation.

I Wonder if there is a way add to your code a way to specify the wished notation to allow it reach your function    loadDoctrineConfiguration(Application $app), 

maybe adding
                    'ORMPrefix' => true/falsevalue,
the configutarion array 
            'entities' => array(
                array(
                    'type' => 'annotation', 
                    'path' => 'Entity', 
                    'namespace' => 'Entity',
                    'ORMPrefix' => 'false',
                )
and the using it in
$driver = $config->newDefaultAnnotationDriver((array)$entity['path'],$entity['ORMPrefix']);

could do the magic.

Sorry for using issues tab, I'm a noob in Github

Thanks again.

**Comment by Taluu** [comment]
Hi,

Thanks for your interest, but the thing is, I'm not maintaining this provider anymore. I think you should check [B. Simensen's ORM Service Provider](https://github.com/dflydev/dflydev-doctrine-orm-service-provider), which provides the feature you're looking for (I know, I was the one to suggest it to him :D) through an option.

**Comment by julietaCuadrado** [comment]
Hi,
Thanks a lot!

2013/3/16 Baptiste Clavié notifications@github.com
