### ISSUE TITLE
Update for Silex 1.1

### ISSUE THREAD

**Issue by jrdnrc** [Taluu/nutwerk-orm-extension#2]
Hi,

Currently this service provider only supports Silex 1.0.*, would it be possible to update for 1.1 or 1.2?

Thanks

**Comment by Taluu** [comment]
Hi,

I'm sorry, I'm not maintaining this anymore. I'd suggest you to check up with Beau Simensen's (@simensen) provider, [dflydev/dflydev-doctrine-orm-service-provider](https://github.com/dflydev/dflydev-doctrine-orm-service-provider)

**Comment by jrdnrc** [comment]
Yeah saw that just after I posted this issue! Don't think I was checking versions properly and getting issues with the dflydev library, all sorted now.

**Comment by Taluu** [comment]
No problem ; I updated the readme to indicate that I'm not maintaining it, as it wasn't written (I was just suggesting the dflydev library).
